import React from 'react';
import './listAtlantic.scss'

const ListAtlantic = () => {
    return ( 
        <article className='list'>
        <p className='list__text list__text--title'>List do sympatyków kina Atlantic</p>
        <p className='list__text list__text--date'>30 września 2020 r.</p>
        <p className='list__text list__text--recipient'>Szanowni Państwo, Sympatycy Kina Atlantic,</p>
        <p className='list__text'>w minionych tygodniach pojawiało się wśród warszawiaków wiele pytań dotyczących losów warszawskiego kina Atlantic. Jako właściciel tego miejsca zdajemy sobie sprawę z jego znaczenia na mapie stolicy. Chcemy więc odpowiedzieć na najczęściej pojawiające się wątpliwości i dzięki temu, jak najszerzej, dotrzeć z informacją o planach dalszego rozwoju kina.
        </p>
        <p className='list__text'><strong>Kino Atlantic pozostanie kinem i nadal będzie otwarte dla miłośników filmu.</strong> Pogłoski o planach sprzedaży działki lub kina czy też budowy innego budynku w jego miejsce są nieprawdziwe. Od co najmniej 6 lat dla zainteresowanych stron jest wiadome, że<strong>od 1 stycznia 2021 r., po wygaśnięciu umowy dzierżawy, kino Atlantic wróci do właściciela, czyli Instytucji Filmowej MAX-FILM.</strong>  Nie jest to proces niezwykły. Często zdarza się, że następuje zmiana operatora kina, która przechodzi tak płynnie, że jest dla widzów właściwie niezauważalna. Mamy doświadczenie w przeprowadzaniu takich zmian oraz w prowadzeniu prac modernizacyjnych w trakcie działania kina. Tak było na przykład w stołecznym kinie Wisła, które nie zostało zamknięte dla widzów nawet na 1 dzień. Dołożymy wszelkich starań, by stało się tak również w kinie Atlantic. Jesteśmy jednak świadomi, że przeszło ono renowację blisko ćwierć wieku temu i od tamtej pory nie było modernizowane. Sale i sprzęt z pewnością wymagają renowacji. Chcemy jednak zadbać o estetykę najstarszego kina w stolicy, dlatego już teraz planujemy odrestaurowanie historycznego neonu i wiele innych prac. Żeby to wszystko zrealizować, niezbędna będzie dobra współpraca z obecnym dzierżawcą i być może mazowieckim konserwatorem zabytków.</p>
        <p className='list__text'>Zamierzamy wykorzystać nasze wieloletnie doświadczenia nie tylko w utrzymaniu, lecz także <strong>w rozwoju kina Atlantic.</strong> MAX-FILM jest członkiem najważniejszych organizacji branżowych w Polsce i Europie, m.in. Sieci Kin Studyjnych i Lokalnych oraz Europa Cinemas. W 2006 r. wszystkie nasze obiekty połączyliśmy marką NoveKino, oferując widzom łącznie blisko 3 000 miejsc. Od stycznia 2021 r. kino Atlantic dołączy do naszej sieci, dzięki czemu jeszcze bardziej zaangażujemy się w nowe projekty związane z rozwojem i promocją kinematografii i kultury w Warszawie. Mamy wiedzę, która pozwoli na poszerzenie oferty tak, aby liczba odwiedzających kino przy ul. Chmielnej stale rosła – i wykorzystamy ją najlepiej, jak potrafimy.</p>
        <p className='list__text'><strong>Zależy nam na doświadczonych pracownikach.</strong> Wiemy, że to ludzie tworzą kino i jego klimat. Doceniamy zaangażowanie obecnego zespołu, dlatego wszyscy pracownicy, którzy od lat są związani z kinem Atlantic, będą mile widziani w dalszej współpracy z nami. Mamy przekonanie, że gwarancją ciągłości działania kina Atlantic jest dobrany i doświadczony zespół.</p>
        <p className='list__text'><strong>MAX-FILM od ponad dekady skupia się przede wszystkim na rozwoju i nowoczesnym zarządzaniu kinami.</strong> Tymczasem w nieprzychylnych artykułach próbuje się uparcie przypisywać nam plany, których nie mamy. Historia spółki jest długa. Działała ona w różnych warunkach i miała na przestrzeni lat różne modele funkcjonowania. Zamiast jednak wracać do decyzji z lat 90.– prosimy, sprawdźcie Państwo, jak jest dziś. Zgodnie z realizowaną od 10 lat strategią skupiamy się na promowaniu kultury, nowoczesnym zarządzaniu kinami, dystrybucji i rozpowszechnianiu filmów. Tę misję realizujemy we wszystkich naszych kinach. Jeśli zechcecie się przekonać – zapraszamy do kina Wisła, gdzie zobaczycie zmiany, które nastąpiły na przestrzeni ostatnich lat. Warszawiacy docenili je, czemu dali wyraz faktyczną obecnością – widownia kina w ciągu ostatniej dekady wzrosła o 130 tys. osób rocznie. Udało się to pomimo konkurencji pobliskich multipleksów, co najlepiej dowodzi, że kino Wisła jest przyjazne, interesujące i przyciąga mieszkańców naszego miasta. Podobny model rozwoju będziemy kontynuować w kinie Atlantic, a potencjał tych kultowych warszawskich kin chcemy wzmocnić np. poprzez wspólne festiwale i eventy.
        </p>
        <p className='list__text'>Mamy nadzieję, że powyższe informacje uspokoją wszystkich sympatyków kina Atlantic. Jako jedna z najbardziej doświadczonych w kraju firm związanych z promocją kina i kinematografii dołożymy wszelkich starań, by kino przy ul. Chmielnej, czyli w sercu stolicy, nadal tętniło życiem.</p>
        <p className='list__text list__text--regards'><strong>Zespół MAX-FILM</strong></p>
        </article>
     );
}
 
export default ListAtlantic;

